export const categoryBgColorMap: { [color: string]: string } = {
  red: "bg-red-400",
  orange: "bg-orange-400",
  amber: "bg-amber-400",
  yellow: "bg-yellow-400",
  lime: "bg-lime-400",
  green: "bg-green-400",
  emerald: "bg-emerald-400",
  teal: "bg-teal-400",
  cyan: "bg-cyan-400",
  sky: "bg-sky-400",
  blue: "bg-blue-400",
  indigo: "bg-indigo-400",
  violet: "bg-violet-400",
  purple: "bg-purple-400",
  fuchsia: "bg-fuchsia-400",
  pink: "bg-pink-400",
  rose: "bg-rose-400",
  slate: "bg-slate-400",
  gray: "bg-gray-400",
  zinc: "bg-zinc-400",
  neutral: "bg-neutral-400",
  stone: "bg-stone-400",
  black: "bg-black",
};

export const categoryTextColorMap: { [color: string]: string } = {
  red: "text-primary-foreground",
  orange: "text-secondary-foreground",
  amber: "text-secondary-foreground",
  yellow: "text-secondary-foreground",
  lime: "text-secondary-foreground",
  green: "text-secondary-foreground",
  emerald: "text-secondary-foreground",
  teal: "text-secondary-foreground",
  cyan: "text-secondary-foreground",
  sky: "text-secondary-foreground",
  blue: "text-primary-foreground",
  indigo: "text-primary-foreground",
  violet: "text-primary-foreground",
  purple: "text-primary-foreground",
  fuchsia: "text-secondary-foreground",
  pink: "text-secondary-foreground",
  rose: "text-primary-foreground",
  slate: "text-secondary-foreground",
  gray: "text-primary-foreground",
  zinc: "text-secondary-foreground",
  neutral: "text-secondary-foreground",
  stone: "text-primary-foreground",
  black: "text-primary-foreground",
};
